version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production:
        dependency-type: "production"
      tooling:
        dependency-type: "development"
        patterns:
          - "@biomejs/*"
          - "typescript"
          - "tsx"
          - "tsdown"
          - "tscw-config"
      bundlers:
        dependency-type: "development"
        patterns:
          - "@rspack/*"
          - "webpack*"
      release:
        dependency-type: "development"
        patterns:
          - "@changesets/*"
          - "@commitlint/*"
          - "husky"
          - "lint-staged"
      misc:
        dependency-type: "development"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
